#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get staged .spec.ts files only
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.spec\.ts$')

if [ -n "$FILES" ]; then
  # Search for `.only` in the staged spec files
  MATCHED=$(echo "$FILES" | xargs grep -n '\.only' || true)

  if [ -n "$MATCHED" ]; then
    echo "$MATCHED"
    echo "❌ Commit blocked: Found '.only' in test files (.spec.ts). Please remove it."
    exit 1
  fi
fi

#Auto-generate index.ts files
pnpm run generate:index

git add .

# Run lint-staged if configured
pnpm dlx lint-staged
